---
title: "Cluster and ID Cell Types"
author: "PP"
date: "2024-03-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, cache.lazy = FALSE, 
                      warning = FALSE, include = FALSE, message = FALSE)
```

``` {r libraries}
library(tidyverse)
library(Seurat)
library(openxlsx)
library(stringr)
library(gridExtra)
library(ggpubr)
library(clustree)
```

``` {r data}
proj_dir <- "~/Documents/PhD/Projects/2022/Meiotic_drive_2022/MeioticDrive2022_Analyses/R_analyses/"
load("~/Documents/PhD/Projects/2022/Meiotic_drive_2022/MeioticDrive2022_Analyses/R_analyses/indata/RData/integrated_seurat_nf200_mtr0.20_gu0.RData")
seurat_integrated$treatment <- "SR"
seurat_integrated$treatment[grep("st", seurat_integrated$sample)] <- "ST"
DefaultAssay(seurat_integrated) <- "integrated"
ortholog_table <- read.csv("~/Documents/PhD/Projects/2022/Meiotic_drive_2022/MeioticDrive2022_Analyses/R_analyses/outdata/orthologs_Jan24.csv")
```


``` {r clustering, include = T}
######### Determining number of PCAs to use for clustering/UMAP etc.
EP <- ElbowPlot(seurat_integrated, ndims = 40)
pct <- seurat_integrated[["pca"]]@stdev / sum(seurat_integrated[["pca"]]@stdev) * 100
# Calculate cumulative percents for each PC
cumu <- cumsum(pct)

# Determine which PC exhibits cumulative percent greater than 90% and % variation associated with the PC as less than 5
co1 <- which(cumu > 90 & pct < 5)[1]

# Determine the difference between variation of PC and subsequent PC
co2 <- sort(which((pct[1:length(pct) - 1] - pct[2:length(pct)]) > 0.1), decreasing = T)[1] + 1

# last point where change of % of variation is more than 0.1%.
pcs <- min(co1, co2)
pcs
seurat_integrated <- RunUMAP(seurat_integrated, dims = 1:pcs, verbose = F)
######### Determining resolution to use --------
seurat_integrated <- FindNeighbors(object=seurat_integrated, dims=1:pcs, verbose = F)
seurat_integrated <- FindClusters(object=seurat_integrated, resolution = c(0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 
                                                            0.75, 1, 1.25, 1.5, 1.75, 2, 
                                                            2.5, 3), verbose = F)
```

```{r clusters_plot, fig.width=10, fig.height=10, include = T}
DefaultAssay(seurat_integrated) <- "integrated"
clusttree <- clustree(seurat_integrated)
CT <- plot(clusttree)
CT_noclusters <- clusttree$data %>% 
  group_by(integrated_snn_res.) %>% 
  summarise(no_clusters = n_distinct(cluster)) %>% 
  rename(resolution = integrated_snn_res.) %>%
  ggplot(aes(x = resolution, y = no_clusters)) +
  geom_point()
CT_noclusters

clustering_plots <- ggarrange(EP, CT, CT_noclusters, ncol = 1, nrow = 3)
ggsave(paste0(proj_dir, "/plots/clustering_plots.pdf"), clustering_plots, height = 30, width = 30)
res <- 'integrated_snn_res.0.4'
Idents(seurat_integrated) <- res
```



```{r markergene_setup}
DefaultAssay(seurat_integrated) <- "RNA"

markers <- read.xlsx(paste0(proj_dir, "indata/markers/TDAL_CONSENSUS_MARKERS130224.xlsx"), sheet = 2)[,c(1,2,3,4,5,7)] %>% 
  filter(!is.na(Confidence))

clusters <- str_split(markers$Celltype, ",") %>% unlist() %>% #remove space at start of string
  gsub("^ ", "", .) %>% unique()

clusters <- c("Spermatocyte", "Spermatid", "Spermatagonia", "Cyst", "Hub", "GSC")
cluster_genes <- list()
for (c in clusters){
  genes<- markers$T.dal_marker[grepl(tolower(c), tolower(markers$Celltype))]
  genes2 <- genes %>% gsub(",", " ", .) %>% 
    str_split(" ") %>% unlist() %>% gsub("\\(|\\)", "", .) %>% 
    gsub("_", "-", .) %>% intersect(rownames(seurat_integrated@assays$RNA@counts))
  cluster_genes[[c]] <- genes2
  
}

mk_genes <- markers$T.dal_marker %>% gsub(",", " ", .) %>% 
  str_split(" ") %>% unlist() %>% gsub("\\(|\\)", "", .) %>% 
  gsub("_", "-", .) %>% intersect(rownames(seurat_integrated@assays$RNA@counts))


dps_list <- lapply(cluster_genes, function(x) DotPlot(seurat_integrated, features = x, assay = "RNA" ) + coord_flip())
dps_all <- DotPlot(seurat_integrated, features = unique(unlist(cluster_genes)), assay = "RNA" ) + coord_flip()
dps <- ggarrange(plotlist = dps_list, ncol = 2, nrow = 4, labels = names(cluster_genes))
#arrange them again but with names as titles
ggsave(paste0(proj_dir, "plots/tdal_markers_dotplot_clus.pdf"), dps, height = 20, width = 20)
ggsave(paste0(proj_dir, "plots/tdal_markers_dotplot_all_clus.pdf"), dps_all, height = 20, width = 14)

dmp <- DimPlot(seurat_integrated, label = T)
ggsave(paste0(proj_dir, "plots/tdal_markers_dimplot_clus.pdf"), dmp, height = 10, width = 10)
```


```{r, fig.width=20, fig.height=40, include = T}
dps
```


```{r, fig.width=10, fig.height=10, include = T}
dmp
```






